// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	AnswerID   int32              `json:"answer_id"`
	QuestionID pgtype.Int4        `json:"question_id"`
	AnswerText pgtype.Text        `json:"answer_text"`
	IsCorrect  pgtype.Bool        `json:"is_correct"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdateAt   pgtype.Timestamp   `json:"update_at"`
}

type Question struct {
	QuestionID   int32              `json:"question_id"`
	QuestionText pgtype.Text        `json:"question_text"`
	AnswerID     pgtype.Int4        `json:"answer_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdateAt     pgtype.Timestamp   `json:"update_at"`
}

type Score struct {
	ScoreID        int32       `json:"score_id"`
	TestID         pgtype.Int4 `json:"test_id"`
	ReadingScore   pgtype.Int4 `json:"reading_score"`
	ListeningScore pgtype.Int4 `json:"listening_score"`
	TotalScore     pgtype.Int4 `json:"total_score"`
}

type Test struct {
	TestID    int32              `json:"test_id"`
	Username  pgtype.Text        `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdateAt  pgtype.Timestamp   `json:"update_at"`
}

type User struct {
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	FullName       pgtype.Text        `json:"full_name"`
	PasswordHashed pgtype.Text        `json:"password_hashed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdateAt       pgtype.Timestamp   `json:"update_at"`
}
