// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64       `json:"id"`
	Owner     string      `json:"owner"`
	TestID    pgtype.Int4 `json:"test_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Answer struct {
	AnswerID   int64              `json:"answer_id"`
	QuestionID pgtype.Int4        `json:"question_id"`
	AnswerText pgtype.Text        `json:"answer_text"`
	IsCorrect  pgtype.Bool        `json:"is_correct"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdateAt   pgtype.Timestamp   `json:"update_at"`
}

type Question struct {
	QuestionID   int64              `json:"question_id"`
	QuestionText pgtype.Text        `json:"question_text"`
	AnswerID     pgtype.Int4        `json:"answer_id"`
	TestName     pgtype.Text        `json:"test_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdateAt     pgtype.Timestamp   `json:"update_at"`
}

type Score struct {
	ScoreID        int64       `json:"score_id"`
	TestID         pgtype.Int4 `json:"test_id"`
	ReadingScore   pgtype.Int4 `json:"reading_score"`
	ListeningScore pgtype.Int4 `json:"listening_score"`
	TotalScore     pgtype.Int4 `json:"total_score"`
}

type Test struct {
	TestID    int64              `json:"test_id"`
	Username  pgtype.Text        `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdateAt  pgtype.Timestamp   `json:"update_at"`
}

type User struct {
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	FullName       string    `json:"full_name"`
	PasswordHashed string    `json:"password_hashed"`
	CreatedAt      time.Time `json:"created_at"`
	UpdateAt       time.Time `json:"update_at"`
}
