// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Answer struct {
	AnswerID   int32
	QuestionID sql.NullInt32
	AnswerText sql.NullString
	IsCorrect  sql.NullBool
	CreatedAt  sql.NullTime
	UpdateAt   sql.NullTime
}

type Question struct {
	QuestionID   int32
	QuestionText sql.NullString
	AnswerID     sql.NullInt32
	CreatedAt    sql.NullTime
	UpdateAt     sql.NullTime
}

type Score struct {
	ScoreID        int32
	TestID         sql.NullInt32
	ReadingScore   sql.NullInt32
	ListeningScore sql.NullInt32
	TotalScore     sql.NullInt32
}

type Test struct {
	TestID    int32
	UserID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdateAt  sql.NullTime
}

type User struct {
	ID             int32
	Username       sql.NullString
	Email          sql.NullString
	PasswordHashed sql.NullString
	CreatedAt      sql.NullTime
	UpdateAt       sql.NullTime
}
